// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxbinrczibrnqccuynhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4YmlucmN6aWJybnFjY3V5bmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MzI1MjcsImV4cCI6MjA3MTQwODUyN30.r7W_0ylJFAqQXJZLt42XFIFWxUnwS4SnhePNG_aFV7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});